import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Roboto } from 'next/font/google'
import localFont from 'next/font/local';

const roboto = Roboto({
  variable: '--roboto',
  weight: '300',
  subsets: ['latin'],
})

export const arame = localFont({
  variable: '--arame',
  display: 'swap',
  src: [
    {
      path: './fonts/Arame/Arame.ttf',
      weight: '400',
      style: 'normal',
    },
  ],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${arame.variable} overflow-x-hidden bg-dark`}>{children}</body>
    </html>
  );
}
